### ISSUE TITLE
roles/openshift_ca - 'dict object' has no attribute 'master'

### ISSUE THREAD

**Issue by gbenhaim** [openshift/openshift-ansible#8157]
#### Description

When running `playbooks/deploy_cluster.yml` I'm having ` 'dict object' has no attribute 'master'` error in `openshift_ca` role.

##### Version

```
ansible 2.5.1

openshift-ansible-3.9.26-1
```

##### Steps To Reproduce
Run `playbooks/deploy_cluster.yml` with 1 master and 2 nodes.

##### Expected Results
Installation to finish with sucess

```
TASK [openshift_ca : Create the master certificates if they do not already exist] ****************************************************************
Thursday 26 April 2018  18:29:40 +0300 (0:00:01.722)       0:35:41.696 ******** 
fatal: [lago-master]: FAILED! => {}

MSG:

The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'master'

The error appears to have been in '/home/gbenhaim/github/kubevirt-ansible/openshift-ansible/roles/openshift_ca/tasks/main.yml': line 89, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# This should NOT replace the CA due to --overwrite=false when a CA already exists.
- name: Create the master certificates if they do not already exist
  ^ here
```
##### Additional Information

```
OS - Centos 7.4
inventory - https://gist.github.com/gbenhaim/bc1b1a49d4a1641c7c68b0931261d5c0
My setup worked fine with `openshift-ansible-3.9.0-0.40.0`
```

**Comment by vrutkovs** [comment]
Ansible 2.5.1 is not supported, so you might have hit https://github.com/ansible/ansible/issues/38271?

Please try again on ansible 2.4 and attach the full ansible output

**Comment by alexxa** [comment]
@vrutkovs, but [README](https://github.com/openshift/openshift-ansible/blame/master/README.md#L64) says `Ansible >= 2.4.3.0`, should it maybe be updated then?

**Comment by vrutkovs** [comment]
@alexxa good catch, created https://github.com/openshift/openshift-ansible/pull/8198

**Comment by alexxa** [comment]
@vrutkovs thank you

**Comment by gbenhaim** [comment]
`FATAL: Current Ansible version (2.4.2.0) is not supported. Supported versions: 2.4.3.0 or newer`

Unfortunately, I didn't find ansible 2.3.4.0 for centos.

**Comment by lucallero** [comment]
> `FATAL: Current Ansible version (2.4.2.0) is not supported. Supported versions: 2.4.3.0 or newer`
> 
> Unfortunately, I didn't find ansible 2.3.4.0 for centos.

Have you found a solution? Got exactly the same error.

**Comment by vrutkovs** [comment]
Ansible 2.4 is available in https://cbs.centos.org/repos/configmanagement7-ansible-24-testing/x86_64/os/
