### ISSUE TITLE
Issues installing Origin 3.7 on AWS

### ISSUE THREAD

**Issue by mlbiam** [openshift/openshift-ansible#6625]
#### Description

I'm attempting to install Origin 3.7 on AWS.  I want to use s3 as the registry store and EBS for PVs but I'm building out my own instances.  This same setup worked in 3.6.  I'm running into two issues.  The first issue appears that the `Zone` from the `Global` section of the inventory:

```
TASK [openshift_cloud_provider : Configure AWS cloud provider] *******************************
fatal: [10.0.4.160]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'provider'\n\nThe error appears to have been in '/root/openshift-ansible/roles/openshift_cloud_provider/tasks/aws.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Configure AWS cloud provider\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'provider'"}

NO MORE HOSTS LEFT ***************************************************************************
	to retry, use: --limit @/root/openshift-ansible/playbooks/byo/config.retry

PLAY RECAP ***********************************************************************************
10.0.4.144                 : ok=49   changed=3    unreachable=0    failed=0   
10.0.4.160                 : ok=205  changed=17   unreachable=0    failed=1   
localhost                  : ok=11   changed=0    unreachable=0    failed=0   


INSTALLER STATUS *****************************************************************************
Initialization             : Complete
Health Check               : Complete
etcd Install               : Complete
Master Install             : In Progress
	This phase can be restarted by running: playbooks/byo/openshift-master/config.yml
```
In order to get past this error, I had to replace `{{ openshift.provider.zone }}` with `us-east-1a`.  Once I did that, the playbook would run until 

```
TASK [openshift_hosted : Add the secret to the registry's pod service accounts] ******************
Friday 05 January 2018  16:40:03 +0000 (0:00:00.943)       0:21:11.451 ******** 
changed: [10.0.4.194] => (item=registry)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'find_secret'
failed: [10.0.4.194] (item=default) => {"changed": false, "item": "default", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mT6CDW/ansible_module_oc_serviceaccount_secret.py\", line 1700, in <module>\n    main()\n  File \"/tmp/ansible_mT6CDW/ansible_module_oc_serviceaccount_secret.py\", line 1693, in main\n    rval = OCServiceAccountSecret.run_ansible(module.params, module.check_mode)\n  File \"/tmp/ansible_mT6CDW/ansible_module_oc_serviceaccount_secret.py\", line 1643, in run_ansible\n    if not oc_sa_sec.exists(params['secret']):\n  File \"/tmp/ansible_mT6CDW/ansible_module_oc_serviceaccount_secret.py\", line 1560, in exists\n    result = self.service_account.find_secret(in_secret)\nAttributeError: 'NoneType' object has no attribute 'find_secret'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

NO MORE HOSTS LEFT *******************************************************************************

PLAY RECAP ***************************************************************************************
10.0.4.157                 : ok=182  changed=67   unreachable=0    failed=0   
10.0.4.194                 : ok=373  changed=152  unreachable=0    failed=1   
localhost                  : ok=12   changed=0    unreachable=0    failed=0   


INSTALLER STATUS *********************************************************************************
Initialization             : Complete
Health Check               : Complete
etcd Install               : Complete
Master Install             : Complete
Master Additional Install  : Complete
Node Install               : Complete
Hosted Install             : In Progress
	This phase can be restarted by running: playbooks/byo/openshift-cluster/openshift-hosted.yml

Friday 05 January 2018  16:40:05 +0000 (0:00:01.863)       0:21:13.314 ******** 
=============================================================================== 
openshift_hosted : Ensure OpenShift pod correctly rolls out (best-effort today) --------- 607.90s
openshift_node : restart node ----------------------------------------------------------- 126.60s
openshift_node : Start and enable node --------------------------------------------------- 63.36s
openshift_node : Install Node package ---------------------------------------------------- 24.26s
Run health checks (install) - EL --------------------------------------------------------- 18.37s
openshift_ca : Install the base package for admin tooling -------------------------------- 14.23s
openshift_cli : Install clients ---------------------------------------------------------- 12.27s
os_firewall : need to pause here, otherwise the iptables service starting can sometimes cause ssh to fail -- 10.07s
os_firewall : need to pause here, otherwise the iptables service starting can sometimes cause ssh to fail -- 10.06s
openshift_hosted : Create OpenShift router ------------------------------------------------ 7.50s
initialize openshift repos ---------------------------------------------------------------- 7.37s
Run openshift_sanitize_inventory to set variables ----------------------------------------- 7.07s
openshift_version : Get available origin version ------------------------------------------ 7.02s
openshift_hosted_facts : Set hosted facts ------------------------------------------------- 6.56s
openshift_hosted_facts : Set hosted facts ------------------------------------------------- 6.46s
openshift_node : Install Ceph storage plugin dependencies --------------------------------- 6.32s
openshift_master : Start and enable master api on first master ---------------------------- 6.23s
openshift_hosted_facts : Set hosted facts ------------------------------------------------- 6.19s
openshift_hosted_facts : Set hosted facts ------------------------------------------------- 5.80s
restart master api ------------------------------------------------------------------------ 5.47s


Failure summary:


  1. Hosts:    10.0.4.194
     Play:     Create Hosted Resources - registry
     Task:     Add the secret to the registry's pod service accounts
     Message:  All items completed
```
I tried this both with and without trying to use s3 as the registry storage with the same results.  No images in the node or the master docker.  Here's my inventory:

```
[OSEv3]

[OSEv3:children]
masters
nodes
etcd

[OSEv3:vars]
ansible_ssh_user=root
openshift_deployment_type=origin
openshift_master_cluster_hostname=XXXXXXXXXXXXXXXXXXXXXx
openshift_master_cluster_public_hostname=XXXXXXXXXXXXXXXXX
openshift_master_api_port=443
openshift_master_console_port=443
openshift_clusterid=XXXXXXXXXXXXXXXXXX

openshift_clock_enabled=true
openshift_cloudprovider_kind=aws
openshift_cloudprovider_aws_access_key=XXXXXXXXXXXXXXXXxx
openshift_cloudprovider_aws_secret_key=XXXXXXXXXXXXXXXXXXXx

openshift_disable_check=disk_availability,memory_availability

openshift_master_identity_providers=[{"name": "unison","challenge": false,"login": true,"mappingMethod": "claim","kind": "OpenIDIdentityProvider","clientID": "openshift","clientSecret": "xxxxxxxxxxxx","claims": {"id": ["sub"],"preferredUsername": ["preferred_username"],"name": ["name"],"email": ["email"]},"urls": {"authorize": "xxxxxxxxxxxxx","token":"xxxxxxxxxx"}}]

# S3 bucket must already exist.
openshift_hosted_registry_storage_kind=object
openshift_hosted_registry_storage_provider=s3
openshift_hosted_registry_storage_s3_encrypt=false
openshift_hosted_registry_storage_s3_kmskeyid=xxxxxxxxxxxxx
openshift_hosted_registry_storage_s3_accesskey=xxxxxxxxxxxx
openshift_hosted_registry_storage_s3_secretkey=xxxxxxxxxxxxxxxxx
openshift_hosted_registry_storage_s3_bucket=xxxxx
openshift_hosted_registry_storage_s3_region=us-east-1
openshift_hosted_registry_storage_s3_chunksize=26214400
openshift_hosted_registry_storage_s3_rootdirectory=/registry
openshift_hosted_registry_pullthrough=true
openshift_hosted_registry_acceptschema2=true
openshift_hosted_registry_enforcequota=true




[openshift_ca]
a.a.a.a

[masters]
a.a.a.a

[etcd]
a.a.a.a

[nodes]
b.b.b.b

[Global]
Zone=us-east-1a
```

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM or
`atomic-openshift-utils`

* The output of `rpm -q atomic-openshift-utils openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE

# ansible --version
ansible 2.4.2.0
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

# git describe
openshift-ansible-3.7.19-1

# rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.7.13-1.el7.noarch
openshift-ansible-3.7.13-1.el7.noarch


```

##### Steps To Reproduce
1. Launch 1 instance for ansible
2. Launch 2 M5.Large instances - 1 node and 1 master, on CentOS 7 with an extra 20GB disk volume for docker storage
3.  Create S3 bucket
4.  Create IAM user with admin access
5.  Follow instructions at https://docs.openshift.org/latest/install_config/install/host_preparation.html#installing-docker
6.  `ansible playbooks/byo/config.yml`

##### Expected Results
Running origin 3.7

```
Example command and output or error messages
```

##### Observed Results
Master is deployed, I can login but i can't pull down images or provision storage

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)

CentOS Linux release 7.4.1708 (Core)

* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by holgerreif** [comment]
```
fatal: [10.0.4.160]: FAILED! => {"failed": true, "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'provider'\n\nThe error appears to have been in '/root/openshift-ansible/roles/openshift_cloud_provider/tasks/aws.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Configure AWS cloud provider\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'provider'"}
```

We run into the very same problem.

Root cause was: we had configured a proxy but forgot to set a `no_proxy` entry for 169.254.169.254.
Once we had this ip excluded, ansible could gather the required information from instance metadata and correctly set this fact.

**Comment by mlbiam** [comment]
took me a while to get back to this, turns out the issue was because i was trying to use the new M5 instances and openshift doesn't work well with them.  Even after hard coding the regions to get past this issue mounting EBS didn't work either.  rebuilt as M4s and everything worked great.

**Comment by DanyC97** [comment]
@mlbiam are you using any out of the box AMI or just a standard centos/ rhel ami ? just curious if there is already a ready to use AMI with most dependencies required by Openshift - ie - docker version 1.12, ip_forward =1 etc etc

**Comment by mlbiam** [comment]
@DanyC97 i'm using the standard centos7 ami from the aws marketplace

**Comment by nccurry** [comment]
I am able to successfully deploy OpenShift on M5 instances, so I do not think that is the root cause.

**Comment by AndreaFerraresi** [comment]
Same here, any clue?
