### ISSUE TITLE
failed in "Gather Cluster facts" when version >= 3.11.60

### ISSUE THREAD

**Issue by mslovy** [openshift/openshift-ansible#10956]
I meet the error below when switch to openshift-ansible 3.11.60 or later version, the version before 3.11.58 works well.

failed task listed below:
TASK [Gather Cluster facts] *******************************************************************************************************************************************
Saturday 05 January 2019  13:37:46 +0800 (0:00:00.763)       0:00:22.303 ****** 
fatal: [openshift-master-1]: FAILED! => {"changed": false, "module_stderr": "KeyError('ansible_os_family',)\nTraceback (most recent call last):\n  File \"<stdin>\", li
ne 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_openshift_facts_payload_rsh
n4T/__main__.py\", line 1300, in <module>\n  File \"/tmp/ansible_openshift_facts_payload_rshn4T/__main__.py\", line 1287, in main\n  File \"/tmp/ansible_openshift_fact
s_payload_rshn4T/__main__.py\", line 1039, in __init__\n  File \"/tmp/ansible_openshift_facts_payload_rshn4T/__main__.py\", line 1061, in generate_facts\n  File \"/tmp
/ansible_openshift_facts_payload_rshn4T/__main__.py\", line 1194, in init_provider_facts\n  File \"/tmp/ansible_openshift_facts_payload_rshn4T/__main__.py\", line 345,
 in normalize_provider_facts\n  File \"/tmp/ansible_openshift_facts_payload_rshn4T/__main__.py\", line 310, in normalize_openstack_facts\nAttributeError: 'list' object
 has no attribute 'split'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [openshift-master-2]: FAILED! => {"changed": false, "module_stderr": "KeyError('ansible_os_family',)\nTraceback (most recent call last):\n  File \"<stdin>\", li
ne 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_openshift_facts_payload_1Ue
aAB/__main__.py\", line 1300, in <module>\n  File \"/tmp/ansible_openshift_facts_payload_1UeaAB/__main__.py\", line 1287, in main\n  File \"/tmp/ansible_openshift_fact
s_payload_1UeaAB/__main__.py\", line 1039, in __init__\n  File \"/tmp/ansible_openshift_facts_payload_1UeaAB/__main__.py\", line 1061, in generate_facts\n  File \"/tmp
/ansible_openshift_facts_payload_1UeaAB/__main__.py\", line 1194, in init_provider_facts\n  File \"/tmp/ansible_openshift_facts_payload_1UeaAB/__main__.py\", line 345,
 in normalize_provider_facts\n  File \"/tmp/ansible_openshift_facts_payload_1UeaAB/__main__.py\", line 310, in normalize_openstack_facts\nAttributeError: 'list' object
 has no attribute 'split'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
fatal: [openshift-master-3]: FAILED! => {"changed": false, "module_stderr": "KeyError('ansible_os_family',)\nTraceback (most recent call last):\n  File \"<stdin>\", li
ne 113, in <module>\n  File \"<stdin>\", line 105, in _ansiballz_main\n  File \"<stdin>\", line 48, in invoke_module\n  File \"/tmp/ansible_openshift_facts_payload_J3p
iMl/__main__.py\", line 1300, in <module>\n  File \"/tmp/ansible_openshift_facts_payload_J3piMl/__main__.py\", line 1287, in main\n  File \"/tmp/ansible_openshift_fact
s_payload_J3piMl/__main__.py\", line 1039, in __init__\n  File \"/tmp/ansible_openshift_facts_payload_J3piMl/__main__.py\", line 1061, in generate_facts\n  File \"/tmp
/ansible_openshift_facts_payload_J3piMl/__main__.py\", line 1194, in init_provider_facts\n  File \"/tmp/ansible_openshift_facts_payload_J3piMl/__main__.py\", line 345,
 in normalize_provider_facts\n  File \"/tmp/ansible_openshift_facts_payload_J3piMl/__main__.py\", line 310, in normalize_openstack_facts\nAttributeError: 'list' object
 has no attribute 'split'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by X-dark** [comment]
I am getting the same error but only on my apps nodes...

**Comment by X-dark** [comment]
This is a regression introduced by this https://github.com/openshift/openshift-ansible/commit/8961c95104ebed20c731eba0f758ab764fb2804d when you are not using floating ip

**Comment by therevoman** [comment]
I also experienced this issue when trying to apply 3.9.60.  Worked fine in 3.9.51

```TASK [Gather Cluster facts] ***************************************************************************************************************************************************************************************************************************** task path: /usr/share/ansible/openshift-ansible/playbooks/init/cluster_facts.yml:9 Monday 14 January 2019 13:29:05 +0000 (0:00:00.096) 0:00:08.235 ******** An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'split' fatal: [cae-idev-np-alln-master-host-0.cisco.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1678, in <module>\n main()\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1665, in main\n additive_facts_to_overwrite)\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1331, in __init__\n additive_facts_to_overwrite)\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1361, in generate_facts\n provider_facts = self.init_provider_facts()\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 1503, in init_provider_facts\nprovider_info.get('metadata')\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 375, in normalize_provider_facts\n facts = normalize_openstack_facts(metadata, facts)\n File \"/tmp/ansible_oAT2PW/ansible_module_openshift_facts.py\", line 340, in normalize_openstack_facts\n if socket.gethostbyname(metadata['ec2_compat'][h_var]) == metadata['ec2_compat'][ip_var].split(',')[0]:\nAttributeError: 'list' object has no attribute 'split'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}``

**Comment by mslovy** [comment]
@X-dark   how can I work around it？ when I am not  using floatingip

**Comment by X-dark** [comment]
@mslovy revert commit 8961c95

**Comment by mslovy** [comment]
thanks, switch to 3.11.70 and solve it

**Comment by jukito** [comment]
Same problem here

> thanks, switch to 3.11.70 and solve it

How do you switch to desired version?
I'm trying to pass prerequisites with same issue with:

`atomic install --system --storage=ostree --set INVENTORY_FILE=/etc/ansible/hosts --set PLAYBOOK_FILE=/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml --set OPTS="-vvv" docker.io/openshift/origin-ansible:v3.11`

Of course, properly configured inventory on /etc/ansible/hosts


Thanks a lot!
