### ISSUE TITLE
failed provider GitHubIdentityProvider missing required key clientID|clientSecret

### ISSUE THREAD

**Issue by jfchevrette** [openshift/openshift-ansible#9913]
#### Description

Install fails when validating openshift_master_identity_providers

##### Version
```
ansible 2.6.3
  config file = /home/os-admin/cluster/ansible.cfg
  configured module search path = [u'/home/os-admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

openshift-ansible-3.10.41-1.git.0.fd15dd7.el7.noarch
```

##### Steps To Reproduce
1. group_vars/masters
```
openshift_master_identity_providers:
- name: github
  kind: GitHubIdentityProvider
  challenge: false
  login: true
  mappingMethod: add
  provider:
    kind: GitHubIdentityProvider
    apiVersion: v1
    clientID: xyz
    clientSecret: xyz
    organizations:
    - my-org
- name: htpasswd
  kind: HTPasswdPasswordIdentityProvider
  challenge: true
  login: true
  mappingMethod: claim
  provider:
    kind: HTPasswdPasswordIdentityProvider
    apiVersion: v1
    file: /etc/origin/master/users.htpasswd

openshift_master_htpasswd_file: "{{inventory_dir}}/users.htpasswd"
```

##### Expected Results
The above `openshift_master_identity_providers` should be valid. This was working fine in 3.7 and 3.9. My config is valid according to the docs here: https://docs.okd.io/3.10/install_config/configuring_authentication.html#GitHub

##### Observed Results
Error indicating it is missing `clientSecret` or `clientSecret`. 
```
Message:  |failed provider GitHubIdentityProvider missing required key clientID
```

If I duplicate `clientSecret` and `clientSecret` under the top level item it works.

Moreover notice I also have to duplicate the `kind` key otherwise I get the following error on validating the `HTPasswdPasswordIdentityProvider` provider: (this should probably be opened as a separate bug?)

```
The conditional check 'item.kind == 'HTPasswdPasswordIdentityProvider'' failed. The error was: error while evaluating conditional (item.kind == 'HTPasswdPasswordIdentityProvider'): 'dict object' has no attribute 'kind'
               
               The error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_control_plane/tasks/htpass_provider.yml': line 2, column 3, but may
               be elsewhere in the file depending on the exact syntax problem.
```

**Comment by jfchevrette** [comment]
```
Message:  |failed provider GitHubIdentityProvider contains unknown keys provider
```

Are every IDP settings supposed to move out of the `provider` key?
