### ISSUE TITLE
Does not support Ansible 2.6 and greater

### ISSUE THREAD

**Issue by tliron** [openshift/openshift-ansible#11819]
#### Description

Running OpenStack playbooks works on Ansible 2.5.15, but breaks on Ansible 2.6 and greater.

The documentation clearly states `Ansible >= 2.8.2` but does not seem to have been tested with Ansible 2.6+.

##### Version

Playbooks are cloned from this repository with the `release-3.11` branch.

**Comment by vrutkovs** [comment]
It is being tested with Ansible 2.6 (see https://github.com/openshift/openshift-ansible/pull/11274) and 2.7 for Openshift 3.11. What exactly breaks when you run the playbooks? Which Openshift version are you using?

**Comment by tliron** [comment]
Well, first of all the version comparison seems wrong. Trying with Ansible 2.6.18 gives me this error:
```
FATAL: Current Ansible version (2.6.18) is not supported. Supported versions: 2.6.2 or newer
```
Second, let's try 2.6.2. I get this error (and the same error with any Ansible >= 2.6):
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'items'
fatal: [localhost]: FAILED! => {"attempts": 5, "changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ZLJxCH/ansible_module_os_stack.py\", line 267, in <module>\n    main()\n  File \"/tmp/ansible_ZLJxCH/ansible_module_os_stack.py\", line 247, in main\n    stack = _create_stack(module, stack, cloud, sdk)\n  File \"/tmp/ansible_ZLJxCH/ansible_module_os_stack.py\", line 164, in _create_stack\n    **module.params['parameters'])\n  File \"/home/manager/.local/lib/python2.7/site-packages/openstack/cloud/_orchestration.py\", line 90, in create_stack\n    environment_files=environment_files\n  File \"/home/manager/.local/lib/python2.7/site-packages/openstack/orchestration/v1/_proxy.py\", line 62, in read_env_and_templates\n    list(tpl_files.items()) + list(envfiles.items())\nAttributeError: 'NoneType' object has no attribute 'items'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by tliron** [comment]
Note that the above is with Python 2. Switching to Python 3 actually gives a different result -- on Python 3, I cannot run on Ansible 2.5.15 at all because the version checking seems to work differently and succeeds in stopping me. So, on Python 3 I get this error:
```
FATAL: Current Ansible version (2.5.15) is not supported. Supported versions: 2.6.2 or newer
```

**Comment by vrutkovs** [comment]
Sounds like version comparison is broken (cc @mtnbikenc).

Which branch and commit are you using?

**Comment by tliron** [comment]
Sorry, I made a mistake in the above comment -- the issue is not Python 2 versus Python 3. The results are the same in each version of Python. The difference is either using branch `release-3.11` or tag `v3.11`. The branch *does* allow me to use Ansible 2.5.15. The tag *does not* and stops the playbook.

**Comment by vrutkovs** [comment]
Oh, I see. Tag is not "latest 3.11" but rather "initial 3.11 version".

Is this still reproducible on `release-3.11` branch?

**Comment by tliron** [comment]
Yes, I just tested an hour ago with a fresh clone. I'm happy to test any suggested patches!

**Comment by vrutkovs** [comment]
See https://github.com/openshift/openshift-ansible/blob/master/.github/ISSUE_TEMPLATE.md - please attach OS, python and logs info, make sure you run ansible-playbook with `-vvv` switches, paste logs and inventory in gist/pastebin

**Comment by Colstuwjx** [comment]
@tliron The version check issue should be fixed starting at [PR #10535](https://github.com/openshift/openshift-ansible/pull/10535).

BTW, @vrutkovs , shall we make the tag version also be rolling out, since the micro version is still 3.11.0, and it's been walked many commits so far.

Thanks.

**Comment by vrutkovs** [comment]
There won't be any tags in 3.x

Fixed in  #10535
