### ISSUE TITLE
FAILED - RETRYING: Wait for control plane pods to appear

### ISSUE THREAD

**Issue by greencar34** [openshift/openshift-ansible#11739]
#### Description
Trying to install Openshift 3.11 on Baremetal. Got stuck at below error. 
TASK [openshift_control_plane : Wait for control plane pods to appear] *****************************************************************************************************
Monday 01 July 2019  17:19:25 -0400 (0:00:00.091)       0:11:39.499 *********** 
FAILED - RETRYING: Wait for control plane pods to appear (60 retries left).

##### Version

* Your ansible version per `ansible --version`
ansible 2.8.1

If you're running from playbooks installed via RPM

rpm -q openshift-ansible
openshift-ansible-3.11.123-1.git.0.db681ba.el7.noarch

##### Steps To Reproduce
1. [step 1] playbooks/deploy_cluster.yml

##### Expected Results
Describe what you expected to happen.

```
Successful Installation```

##### Observed Results
Describe what is actually happening.

```
INSTALLER STATUS ***********************************************************************************************************************************************************
Initialization              : Complete (0:01:16)
Health Check                : Complete (0:02:16)
Node Bootstrap Preparation  : Complete (0:05:02)
etcd Install                : Complete (0:00:56)
Master Install              : In Progress (0:18:47)
	This phase can be restarted by running: playbooks/openshift-master/config.yml
Monday 01 July 2019  17:36:03 -0400 (0:00:00.041)       0:28:17.407 *********** 
=============================================================================== 
openshift_control_plane : Wait for control plane pods to appear --------------------------------------------------------------------------------------------------- 991.93s
Run health checks (install) - EL ---------------------------------------------------------------------------------------------------------------------------------- 135.22s
openshift_node : install needed rpm(s) ----------------------------------------------------------------------------------------------------------------------------- 46.30s
Gathering Facts ---------------------------------------------------------------------------------------------------------------------------------------------------- 28.12s
openshift_node : Install GlusterFS storage plugin dependencies ----------------------------------------------------------------------------------------------------- 23.28s
Gathering Facts ---------------------------------------------------------------------------------------------------------------------------------------------------- 22.18s
openshift_node : Install node, clients, and conntrack packages ----------------------------------------------------------------------------------------------------- 22.07s
openshift_excluder : Install docker excluder - yum ----------------------------------------------------------------------------------------------------------------- 12.61s
openshift_excluder : Install openshift excluder - yum -------------------------------------------------------------------------------------------------------------- 12.28s
tuned : Ensure files are populated from templates ------------------------------------------------------------------------------------------------------------------ 11.73s
openshift_ca : Install the base package for admin tooling ---------------------------------------------------------------------------------------------------------- 10.04s
openshift_cli : Install clients ------------------------------------------------------------------------------------------------------------------------------------- 9.86s
openshift_node : Install iSCSI storage plugin dependencies ---------------------------------------------------------------------------------------------------------- 7.04s
nickhammond.logrotate : nickhammond.logrotate | Install logrotate --------------------------------------------------------------------------------------------------- 6.39s
openshift_control_plane : Copy static master scripts ---------------------------------------------------------------------------------------------------------------- 6.18s
openshift_node : Install NFS storage plugin dependencies ------------------------------------------------------------------------------------------------------------ 5.58s
openshift_node : restart services ----------------------------------------------------------------------------------------------------------------------------------- 5.58s
openshift_node : Install Ceph storage plugin dependencies ----------------------------------------------------------------------------------------------------------- 5.53s
openshift_control_plane : Prepare master static pods ---------------------------------------------------------------------------------------------------------------- 5.51s
openshift_node : Install dnsmasq ------------------------------------------------------------------------------------------------------------------------------------ 5.49s

Failure summary:

  1. Hosts:  
     Play:     Configure masters
     Task:     Report control plane errors
     Message:  Control plane pods didn't come up
```

For long output or logs, consider using a [gist](https://gist.github.com/)


##### Additional Information

Provide any additional information which may help us diagnose the
issue.

Red Hat Enterprise Linux Server release 7.6 (Maipo)
Hostname Comes up with fqdm. 

 master-logs api api
Component api is stopped or not running

```
EXTRA INFORMATION GOES HERE
```

**Comment by dove-young** [comment]
I got similar problem of `FAILED - RETRYING: Wait for control plane pods to appear`

Here is my ansible playbook outut. Pod `master-api-agentavtone-worker3.fyre.ibm.com` was found from beginning and it could get result each time it tried. 

But the playbook just ignore it and treat it as a failure and loop back. 

```
FAILED - RETRYING: Wait for control plane pods to appear (37 retries left).Result was: {
    "ansible_module_results": {
        "cmd": "/usr/bin/oc get pod master-api-agentavtone-worker3.fyre.ibm.com -o json -n kube-system",
        "results": [
            {
                "apiVersion": "v1",
                "kind": "Pod",
                "metadata": {
                    "annotations": {
                        "kubernetes.io/config.hash": "b24b15710309f0062b93e07af49cb464",
                        "kubernetes.io/config.mirror": "b24b15710309f0062b93e07af49cb464",
                        "kubernetes.io/config.seen": "2019-11-19T20:21:13.292191745-08:00",
                        "kubernetes.io/config.source": "file",
                        "scheduler.alpha.kubernetes.io/critical-pod": ""
                    },
                    "creationTimestamp": "2019-11-20T04:22:22Z",
                    "labels": {                                                                                                          "openshift.io/component": "api",
                        "openshift.io/control-plane": "true"
                    },                                                                                                               "name": "master-api-agentavtone-worker3.fyre.ibm.com",
                    "namespace": "kube-system",
                    "resourceVersion": "964",
                    "selfLink": "/api/v1/namespaces/kube-system/pods/master-api-agentavtone-worker3.fyre.ibm.com"
,
                    "uid": "59270297-0b4d-11ea-bdff-00000a150d59"
                },
                "spec": {
                    "containers": [
                        {
                            "args": [
                                "#!/bin/bash\nset -euo pipefail\nif [[ -f /etc/origin/master/master.env ]]; then\
n  set -o allexport\n  source /etc/origin/master/master.env\nfi\nexec openshift start master api --config=/etc/or
igin/master/master-config.yaml --loglevel=${DEBUG_LOGLEVEL:-2}\n"
                            ],
                            "command": [
                                "/bin/bash",
                                "-c"
                            ],
                            "image": "docker.io/openshift/origin-control-plane:v3.11.0",
                            "imagePullPolicy": "IfNotPresent",
                            "livenessProbe": {
                                "failureThreshold": 3,
                                "httpGet": {
                                    "path": "healthz",
                                    "port": 8443,
                                    "scheme": "HTTPS"
                                },
                                "initialDelaySeconds": 45,
                                "periodSeconds": 10,
                                "successThreshold": 1,
                                "timeoutSeconds": 10
                            },
                            "name": "api",
                            "readinessProbe": {
                                "failureThreshold": 3,
                                "httpGet": {
                                    "path": "healthz/ready",
                                    "port": 8443,
                                    "scheme": "HTTPS"
                                },
                                "initialDelaySeconds": 10,
                                "periodSeconds": 10,
                                "successThreshold": 1,
                                "timeoutSeconds": 10
                            },
                            "resources": {},
                            "securityContext": {                                                                                                 "privileged": true                                                                                           },                                                                                                               "terminationMessagePath": "/dev/termination-log",
                            "terminationMessagePolicy": "File",
```

My playbook comes from git tag `openshift-ansible-3.11.99-1`, ansible version is 2.8.5. 
OS is RHEL 7.6

**Comment by dove-young** [comment]
I checked each result individually, and register it to var `control_check`. 
```
- name: check for control plane pods to appear
  oc_obj:
    state: list
    kind: pod
    name: "master-{{ item }}-{{ l_kubelet_node_name | lower }}"
    namespace: kube-system
  register: control_check
  with_items:
  - "{{ 'etcd' if inventory_hostname in groups['oo_etcd_to_config'] else omit }}"
  ignore_errors: true
- name: debug
  debug:
    var: control_check

- name: check for control plane pods to appear
  oc_obj:
    state: list
    kind: pod
    name: "master-{{ item }}-{{ l_kubelet_node_name | lower }}"
    namespace: kube-system
  register: control_check
  with_items:
  - api
  ignore_errors: true
- name: debug
  debug:
    var: control_check

- name: check for control plane pods to appear
  oc_obj:
    state: list
    kind: pod
    name: "master-{{ item }}-{{ l_kubelet_node_name | lower }}"
    namespace: kube-system
  register: control_check
  with_items:
  - controllers
  ignore_errors: true
- name: debug
  debug:
    var: control_check
```

Then I got these results:

- etcd 
```
TASK [openshift_control_plane : check for control plane pods to appear] *****************************************
task path: /root/OpenShift/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:208
Thursday 21 November 2019  20:22:27 -0800 (0:00:00.119)       0:01:08.248 *****
 [WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.

ok: [10.21.13.89] => (item=etcd) => {
    "ansible_loop_var": "item",
    "ansible_module_results": {
        "cmd": "/usr/bin/oc get pod master-etcd-agentavtone-worker3.fyre.ibm.com -o json -n kube-system",
        "results": [
            {
                "apiVersion": "v1",
                "kind": "Pod",
                "metadata": {
                    "annotations": {
                        "kubernetes.io/config.hash": "ac284571ce8a2bb4081b3bd778a00a76",
                        "kubernetes.io/config.mirror": "ac284571ce8a2bb4081b3bd778a00a76",
                        "kubernetes.io/config.seen": "2019-11-20T00:49:55.311645882-08:00",
                        "kubernetes.io/config.source": "file",
                        "scheduler.alpha.kubernetes.io/critical-pod": ""
                    },
```
- etcd.debug

```
TASK [openshift_control_plane : debug] **************************************************************************
task path: /root/OpenShift/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:218
Thursday 21 November 2019  20:22:28 -0800 (0:00:01.486)       0:01:09.734 *****
ok: [10.21.13.89] => {
    "control_check": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "ansible_loop_var": "item",
                "ansible_module_results": {
                    "cmd": "/usr/bin/oc get pod master-etcd-agentavtone-worker3.fyre.ibm.com -o json -n kube-system",
                    "results": [
                        {
                            "apiVersion": "v1",
                            "kind": "Pod",
                            "metadata": {
                                "annotations": {
                                    "kubernetes.io/config.hash": "ac284571ce8a2bb4081b3bd778a00a76",
                                    "kubernetes.io/config.mirror": "ac284571ce8a2bb4081b3bd778a00a76",
                                    "kubernetes.io/config.seen": "2019-11-20T00:49:55.311645882-08:00",
                                    "kubernetes.io/config.source": "file",
                                    "scheduler.alpha.kubernetes.io/critical-pod": ""
                                },
```

- api 

```
TASK [openshift_control_plane : check for control plane pods to appear] *****************************************
task path: /root/OpenShift/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:222
Thursday 21 November 2019  20:22:28 -0800 (0:00:00.156)       0:01:09.891 *****
 [WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.

ok: [10.21.13.89] => (item=api) => {
    "ansible_loop_var": "item",
    "ansible_module_results": {
        "cmd": "/usr/bin/oc get pod master-api-agentavtone-worker3.fyre.ibm.com -o json -n kube-system",
        "results": [
            {
                "apiVersion": "v1",
                "kind": "Pod",
                "metadata": {
                    "annotations": {
                        "kubernetes.io/config.hash": "b24b15710309f0062b93e07af49cb464",
                        "kubernetes.io/config.mirror": "b24b15710309f0062b93e07af49cb464",
                        "kubernetes.io/config.seen": "2019-11-20T00:49:55.311617342-08:00",
                        "kubernetes.io/config.source": "file",
                        "scheduler.alpha.kubernetes.io/critical-pod": ""
                    },
```
- api.debug

```
TASK [openshift_control_plane : debug] **************************************************************************
task path: /root/OpenShift/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:232
Thursday 21 November 2019  20:22:29 -0800 (0:00:00.904)       0:01:10.795 *****
ok: [10.21.13.89] => {
    "control_check": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "ansible_loop_var": "item",
                "ansible_module_results": {
                    "cmd": "/usr/bin/oc get pod master-api-agentavtone-worker3.fyre.ibm.com -o json -n kube-system",
                    "results": [
                        {
                            "apiVersion": "v1",
                            "kind": "Pod",
                            "metadata": {
                                "annotations": {
                                    "kubernetes.io/config.hash": "b24b15710309f0062b93e07af49cb464",
                                    "kubernetes.io/config.mirror": "b24b15710309f0062b93e07af49cb464",
                                    "kubernetes.io/config.seen": "2019-11-20T00:49:55.311617342-08:00",
                                    "kubernetes.io/config.source": "file",
                                    "scheduler.alpha.kubernetes.io/critical-pod": ""
                                },
```

- controller
```
TASK [openshift_control_plane : check for control plane pods to appear] *****************************************
task path: /root/OpenShift/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:236
Thursday 21 November 2019  20:22:29 -0800 (0:00:00.142)       0:01:10.937 *****
 [WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.

ok: [10.21.13.89] => (item=controllers) => {
    "ansible_loop_var": "item",
    "ansible_module_results": {
        "cmd": "/usr/bin/oc get pod master-controllers-agentavtone-worker3.fyre.ibm.com -o json -n kube-system",
        "results": [
            {
                "apiVersion": "v1",
                "kind": "Pod",
                "metadata": {
                    "annotations": {
                        "kubernetes.io/config.hash": "3210f8756194a0d2e374db4a71b81896",
                        "kubernetes.io/config.mirror": "3210f8756194a0d2e374db4a71b81896",
                        "kubernetes.io/config.seen": "2019-11-20T00:49:55.311635192-08:00",
                        "kubernetes.io/config.source": "file",
                        "scheduler.alpha.kubernetes.io/critical-pod": ""
                    },
```
- controller.debug
```
TASK [openshift_control_plane : debug] **************************************************************************
task path: /root/OpenShift/openshift-ansible/roles/openshift_control_plane/tasks/main.yml:246
Thursday 21 November 2019  20:22:30 -0800 (0:00:00.924)       0:01:11.862 *****
ok: [10.21.13.89] => {
    "control_check": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "ansible_loop_var": "item",
                "ansible_module_results": {
                    "cmd": "/usr/bin/oc get pod master-controllers-agentavtone-worker3.fyre.ibm.com -o json -n kube-system",
                    "results": [
                        {
                            "apiVersion": "v1",
                            "kind": "Pod",
                            "metadata": {
                                "annotations": {
                                    "kubernetes.io/config.hash": "3210f8756194a0d2e374db4a71b81896",
                                    "kubernetes.io/config.mirror": "3210f8756194a0d2e374db4a71b81896",
                                    "kubernetes.io/config.seen": "2019-11-20T00:49:55.311635192-08:00",
                                    "kubernetes.io/config.source": "file",
                                    "scheduler.alpha.kubernetes.io/critical-pod": ""
                                },
```

**Comment by dove-young** [comment]
But the error msg always said
```
 [WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.

fatal: [10.21.13.89]: FAILED! => {
    "msg": "The conditional check 'control_plane_pods.results | length > 0' failed. The error was: error while evaluating conditional (control_plane_pods.results | length > 0): 'dict object' has no attribute 'results'"
}
```

I changed `control_plane_pods.results  | length > 0`  to `ansible_module_results.results | length > 0`, then it fails at 

```
 [WARNING]: Found internal 'results' key in module return, renamed to 'ansible_module_results'.

fatal: [10.21.13.89]: FAILED! => {
    "msg": "The conditional check 'ansible_module_results.results | length > 0' failed. The error was: error whil
e evaluating conditional (ansible_module_results.results | length > 0): 'ansible_module_results' is undefined"
}
```

**Comment by dove-young** [comment]
Find this issue https://github.com/openshift/openshift-ansible/issues/11641#issuecomment-505486761 which said

> Ansible 2.8 should work with the latest 3.11 release since PR #11325 has merged. Minor additional fixes since that PR have also been merged.

But it dose not work with Ansible 2.8

**Comment by mtnbikenc** [comment]
openshift-ansible-3.11.141-1 was validated with Ansible 2.8.4.
https://bugzilla.redhat.com/show_bug.cgi?id=1740842

Please update to at least 3.11.141.
