### PR TITLE
Force reconciliation of role for 3.6

### PR DESCRIPTION
**Pull request by simo5**
This is needed because in 3.6 we cannot reconcile non-cluster roles in the
bootstrap reconciliation code.
In 3.7 this is taken care of in code.

### CODE REVIEW

**Comment by simo5** [comment]
@kwoodson PTAL

File: playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml [hunk 1]
```diff
@@ -231,6 +231,24 @@
     - reconcile_jenkins_role_binding_result.rc == 0
     when: (not openshift.common.version_gte_3_7 | bool) and (openshift.common.version_gte_3_4_or_1_4 | bool)
 
+  - copy:
+      src: "{{ __master_files_location }}/{{ item }}"
+      dest: "{{ tmpdir }}/{{ item }}"
+    with_items:
+    - "{{ __master_shared_resource_viewer_file }}"
+    when: (openshift.common.version_gte_3_6 | bool) and (not openshift.common.version_gte_3_7 | bool)
```
Comment (kwoodson) [inline playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml]: Could use a `block` structure here and place both of these tasks underneath it.

Comment (simo5) [reply playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml]: See how it looks now @kwoodson

**Comment by sdodson** [comment]
@kwoodson @mtnbikenc 

We don't need to deal with it now as we've already got other version specific conditionals in this file, but we should look at what we need to do to move all version specific code out of `playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml`.

We either need to drive that out into `playbooks/common/openshift-cluster/upgrades/v3_6/upgrade_control_plane.yml` or define better internal hooks that we can use to define version specific task lists.

**Comment by kwoodson** [comment]
@sdodson @mtnbikenc, totally agree with the control plane removing version logic.

**Comment by simo5** [comment]
@sdodson can you lgtm if this is ok ?

**Comment by simo5** [comment]
@sdodson I just realize this PR does not test the change due to version gating. Should I push another PR against the release-3.6 branch first and then we commit both when we are sure it work in 3.6 ?
/hold

**Comment by sdodson** [comment]
Yeah, I was setting my host up to test this. I'm also looking to verify
that this happens both when upgrading from 3.5 to 3.6 and when upgrading
from 3.6.N to 3.6.N+1. Is that what you're intending to do?

**Comment by sdodson** [comment]
Fails like this, I'll work on a fix.

```
TASK [copy] *****************************************************************************************************************************************
fatal: [ose3-master.example.com]: FAILED! => {"failed": true, "msg": "The conditional check '(openshift.common.version_gte_3_6 | bool) and (not openshift.common.version_gte_3_7 | bool)' failed. The error was: error while evaluating conditional ((openshift.common.version_gte_3_6 | bool) and (not openshift.common.version_gte_3_7 | bool)): 'dict object' has no attribute 'version_gte_3_7'\n\nThe error appears to have been in '/home/rdu/sdodson/git/Openshift/openshift-ansible/playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml': line 237, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    block:\n    - copy:\n      ^ here\n"}
```

**Comment by simo5** [comment]
Do we need some different gating ?
Maybe you can let it run on all versions so we see if the oc replace part works for now ?

**Comment by sdodson** [comment]
That particular error happened because I had cherry-picked it into release-3.6 and the version_gte_3_7 fact doesn't exist there. We'll either want to add version_gte_3_7 to release-3.6 branch or just drop that part of the conditional and assume that 3.6 version of the playbooks would never be used to upgrade to 3.7. Running this on master I ran into some file path issues and I've resolved those in https://github.com/simo5/openshift-ansible/pull/1

**Comment by enj** [comment]
@simo5 this should not run if the reconcile protect annotation is on the role.

**Comment by simo5** [comment]
@sdodson will this wip change work ?

File: playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml [hunk 2]
```diff
@@ -234,21 +234,36 @@
...
+        state: list
+        kind: role
+        name: "shared-resource-viewer"
+        namespace: "openshift"
+      register: objout
+
+    - name: Determine if shared-resource-viewer is protected
+      set_fact:
+        __shared_resource_viewer_protected: "{{ objout['results']['results']['metadata']['annotations']['openshift.io/reconcile-protect'] }}"
+      when: "'results' in objout and 'results' in objout['results'] and 'openshift.io/reconcile-protect' in objout['results']['results'][0]['metadata']['annotations']"
```
Comment (enj) [inline playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml]: The value of the annotation must be true.  `openshift.io/reconcile-protect==true` means do not reconcile.

Comment (simo5) [reply playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml]: I pushed a version that checks for that

File: playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml [hunk 3]
```diff
@@ -231,6 +232,39 @@
...
+    - name: Fixup shared-resource-viewer role
+      oc_obj:
+        state: present
+        kind: role
+        name: "shared-resource-viewer"
+        namespace: "openshift"
+        files:
+        - "/tmp/{{ __master_shared_resource_viewer_file }}"
+        delete_after: true
+      when: __shared_resource_viewer_protected is not defined
```
Comment (enj) [inline playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml]: We should emit some kind of warning when `__shared_resource_viewer_protected is defined` so the user has a way of knowing that they will need to reconcile this themselves somehow.

Comment (simo5) [reply playbooks/common/openshift-cluster/upgrades/upgrade_control_plane.yml]: I have no idea if there is a way to do that, @sdodson may know ?

**Comment by simo5** [comment]
@sdodson I updated the code copy/pasting what you did in the 3.6 branch.
